internal/exec: switch log level for failed to fetch the config
coreos/ignition pull request #1346
Opened 2022-04-13 15:35 UTC by sohankunkerkar

Fixes https://github.com/coreos/fedora-coreos-tracker/issues/1159

2022-04-13 21:04 UTC, dustymabe commented
I'm not entirely convinced this is the right move. As there might be cases where we want this to be a warning. @bgilbert - WDYT is the right fix for https://github.com/coreos/fedora-coreos-tracker/issues/1159 ?

2022-04-14 02:42 UTC, bgilbert commented
I think this is in the neighborhood of the right fix.  If the error is `ErrNeedNet`, that's a normal outcome and will result in a retry, so let's log at `Info` level.  (I had previously suggested `Notice`, but I think it might be too routine for that.)  For other fetch failures, we should continue logging at `Warning`.  (It's not an `Error` because the user is not required to provide a config.)

2022-04-14 17:03 UTC, dustymabe approved these changes

2022-04-14 17:09 UTC, dustymabe requested changes
let's change to what bgilbert requested where we add a new else and check `if err == error.ErrNeedNet` then we `Info`, but we leave the current `if err != nil` warning at the bottom.

2022-04-14 17:26 UTC, bgilbert approved these changes

2022-04-14 18:50 UTC, merged