config/doc/ignition.yaml: correction in description
coreos/ignition pull request #1930
Opened 2024-08-30 08:21 UTC by madhu-pillai

This PR is raised to correct the sentence in `desc:` for CEX feature in ignition as well as butane. 

Ref: https://github.com/coreos/butane/pull/536#discussion_r1678449662

2024-09-16 14:07 UTC, prestist commented on docs/release-notes.md
> +- Sentence correction in document `luks.cex.enabled.desc`
we can drop this, I dont think we need to add release notes for this change.

2024-09-16 14:07 UTC, prestist requested changes
After you drop the release-notes.md change lgtm, thank you for doing this.

2024-09-16 14:42 UTC, madhu-pillai commented
Hi @prestist ,

Without the release notes it fails the test.  Is there any way to skip this?

2024-09-16 16:03 UTC, dustymabe commented
> Without the release notes it fails the test. Is there any way to skip this?

We could just ignore the test output and merge?

2024-09-20 18:29 UTC, prestist commented
@madhu-pillai there is a label for this, I just added it thank you!

2024-09-20 18:29 UTC, prestist approved these changes
LGTM

2024-09-20 18:29 UTC, merged